# .streamlit/secrets.toml

[mongo]
host = "mongodb+srv://nasagrc:<password>@nasagrclabdatatest.hnx1ick.mongodb.net/?retryWrites=true&w=majority&appName=NASAGRCLabDataTest"
port = 27017
username = "nasagrc"
password = "brookpark21000"
