# .streamlit/secrets.toml

MONGODB_PASSWORD = "brookbark2100"

[mongo]
MONGODB_PASSWORD = "brookbark2100"
#host = "nasagrclabdatatest.hnx1ick.mongodb.net"
#port = 27017
#username = "nasagrc"
#password = "brookpark21000"
