[mongo]
host = "mongodb://atlas-sql-66168d620cd39b0f67a58c6e-lqa6t.a.query.mongodb.net/sample_mflix?ssl=true&authSource=admin"
port = 27017
username = "mongodb+srv://nasagrc"
password = "brookpark21000"
connect = "mongodb+srv://nasagrc:brookpark21000@nasagrclabdatatest.hnx1ick.mongodb.net/?retryWrites=true&w=majority&appName=NASAGRCLabDataTest"
