[mongo]
host = "nasagrclabdatatest.hnx1ick.mongodb.net/"
port = 27017
username = "nasagrc"
password = "brookpark21000"

[connections.gsheets]
spreadsheet = "https://docs.google.com/spreadsheets/d/1ulxTrx0iVzhoJKhUBbegxT4fhOCW6iNSuVWIUSIT7C8/edit?usp=sharing"
