[mongo1]
host = "ac-beezwv1-shard-00-00.hnx1ick.mongodb.net"
port = 27017
username = "nasagrc"
password = "brookpark21000"
bindIP = "0.0.0.0"

[mongo2]
host = "ac-beezwv1-shard-00-01.hnx1ick.mongodb.net"
port = 27017
username = "nasagrc"
password = "brookpark21000"

[mongo3]
host = "ac-beezwv1-shard-00-02.hnx1ick.mongodb.net"
port = 27017
username = "nasagrc"
password = "brookpark21000"
